import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { inter } from "@/lib/fonts";
import Navbar from "@/components/blocks/navbar";
import Footer from "@/components/blocks/footer";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Medcare Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased w-full", inter.className)}>
        <Navbar />
        <main role="main">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
