import type { Metadata, Viewport } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { inter } from "@/lib/fonts";
import Navbar from "@/components/blocks/navbar";
import Footer from "@/components/blocks/footer";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/wrappers/sessionProvider";
// import { Analytics } from "@vercel/analytics/react";
import Providers from "@/components/wrappers/providers";
import { ThemeProvider } from "@/lib/theme-provider";
import TanstackProvider from "@/components/wrappers/tanstackProvider";


export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: false,
  viewportFit: "contain",
};

export const metadata: Metadata = {
  title: "Medcare Hub",
  description: "Generated by create next app",
  verification: {
    google: "Qex2I5k01ZN8QezjCTqKq9xe_1HlSi-T_jrm66DCqQI",
  },
};
export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider>
        <Providers>
          <TanstackProvider>
            <body className={cn("antialiased w-full", inter.className)}>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <Navbar />
                <main role="main">
                  {modal}
                  {children}
                  <Toaster />
                  {/* <Analytics /> */}
                </main>
                <Footer />
              </ThemeProvider>
            </body>
          </TanstackProvider>
        </Providers>
      </AuthProvider>
    </html>
  );
}
