import type { Metadata } from "next";
import "./globals.css";
import { addMaximumScaleToMetaViewport, checkIsIOS, cn } from "@/lib/utils";
import { inter } from "@/lib/fonts";
import Navbar from "@/components/blocks/navbar";
import Footer from "@/components/blocks/footer";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/wrappers/sessionProvider";
import { Analytics } from "@vercel/analytics/react";
import Providers from "@/components/wrappers/providers";

export const metadata: Metadata = {
  title: "Medcare Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <AuthProvider>
        <Providers>
          <body className={cn("antialiased w-full", inter.className)}>
            <Navbar />
            <main role="main">
              {children}
              <Toaster />
              <Analytics />
            </main>
            <Footer />
          </body>
        </Providers>
      </AuthProvider>
    </html>
  );
}
