# .github/workflows/delete-outdated-availabilities.yml

name: Delete Outdated Availabilities

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API to Delete Outdated Availabilities
        env:
          API_URL: ${{ secrets.VERCEL_API_URL }}
        run: |
          curl -X POST "$API_URL/api/doctors/delete-outdated-availabilities"
